### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'group'

### ISSUE THREAD

**Issue by sutcliffe121** [PetzJohannes/laravel-7-8-routes-migration#1]
Hi there,

Nice idea for the script. I gave it a go but get the following error. Any ideas?

----------------------------------------

Converting routes files: routes/web.php
Traceback (most recent call last):
  File "C:\laragon\www\flyuk\laravel-8-route-converter.py", line 193, in <module>
    convert_routes_file(args.routes_file)
  File "C:\laragon\www\flyuk\laravel-8-route-converter.py", line 161, in convert_routes_file
    line = change_route(line)
  File "C:\laragon\www\flyuk\laravel-8-route-converter.py", line 88, in change_route
    controllerName = re.search("[A-Za-z0-9]+Controller", line).group(0)
AttributeError: 'NoneType' object has no attribute 'group'

**Comment by PetzJohannes** [comment]
Hello @sutcliffe121 ,
hm maybe the regex `"[A-Za-z0-9]+Controller"` doesn't match your Controller(s).

You can change the regex to your needs so every Controller will be a match.
Without your routes file it will be hard to debug :)

**Comment by sutcliffe121** [comment]
My controllers seem to fit the regex. Could I email you my routes file? I
dont want to post it public.

It would be great to use your tool.

Chris.

**Comment by PetzJohannes** [comment]
Hi Chris @sutcliffe121 ,
sorry for my late answer. Yes you can email me your routes file.

Cheers
Johannes

**Comment by kenean-50** [comment]
+1 same problem

**Comment by PetzJohannes** [comment]
Can you please share an example of your route file(s)? So I can proper debug it?
@kenean-50 or @sutcliffe121

**Comment by kenean-50** [comment]
all my routes were like this 

`Route::get('dashboard',  'DashboardController@index');`

since there were a lot of them I was hoping it will help me transform them into something like this 

`Route::get('dashboard',  [App\Http\Controllers\DashboardController::class, 'index']);`

**Comment by PetzJohannes** [comment]
But this should work.
Can you copy a couple of routes to a new file and run the script? If the error occurs, anonymize the route names if you want, check again if error occurs and post the "routes" file?

I am unable to debug this without examples, as the examples you gave me, should work.

**Comment by merlin334** [comment]
I had the same problem, fixed it by adding:

        if 'Route::view' in line:
            routes.append(line)
            continue

        if "function" in line:
            routes.append(line)
            continue

after line 115

        if '<?php' in line:
            continue

And another problem on line 130:
Changed 
elif '});' in line and len(line) - len(line.lstrip(' ')) == group:
into
elif '} );' in line and len(line) - len(line.lstrip(' ')) == group:
Add a space after curly brace 
elif '}[space])

Hope it helps, all my routes worked after I have done this.
@PetzJohannes Thank you for the script, saved me a lot of work

**Comment by PetzJohannes** [comment]
@merlin334 your welcome :) Thanks for the feedback.

If you commit your change, I will merge them so everyone can use your fix.

**Comment by merlin334** [comment]
@PetzJohannes  I created the pull request, hopefully my fixes will work fine for others too.

**Comment by PetzJohannes** [comment]
@merlin334 thanks.
unfortunately I cannot merge the request because the line 130, might break other use cases.

Maybe if you add the "space" line into a new `elif`, so the use case für `});` is still valid.

**Comment by PetzJohannes** [comment]
I close this issue. Everyone with the same problem can use your branch :)
